### ISSUE TITLE
Link is not functional

### ISSUE THREAD

**Issue by cerqueiranews** [alexsuter/yii2-tag-cloud#2]
bzz445  wants to merge 1 commit into alexsuter:master from bzz445:master???

**Comment by alexsuter** [comment]
Thank you. At the moment I have no time, i will check that within 2 weeks. sorry.

**Comment by cerqueiranews** [comment]
Ok! Pay attention, he did change the name attribute arrTags to tags, but the fix is fully functional. Sorry my poor english =).

Thanks for great work!

**Comment by alexsuter** [comment]
@cerqueiranews The merge is finally done.

The API is broken - use tags instead of arrTags now. I will make some improvments these days and will release version 2.0.0!

**Comment by alexsuter** [comment]
Version 2.0.1 is released.

**Comment by cerqueiranews** [comment]
Thanks!

*Diego Muniz Cerqueira*
Skype: cerqueiranews
MSN: cerqueiranews@hotmail.com
Gtalk: cerqueiranews@gmail.com
Celular: 21 7101-6062

2016-01-21 10:35 GMT-02:00 Alex <notifications@github.com>:
